### ISSUE TITLE
Frame still jumps between movies

### ISSUE THREAD

**Issue by grinfax** [the-mikedavis/doc_gen#4]
Needs a preloader so the movies seamlessly flow between each other.

**Comment by the-mikedavis** [comment]
Now I'm sending some headers for preloading the videos, but I don't see any difference in jumpiness in my local env. I think some of the jumpiness comes from dynamically changing the `source`'s `src` attribute. I think we can make this better by having some css transitions, but we can't eliminate it entirely.

Another solution is to build a `MediaSource` object and load multiple videos into the same buffer and feed that binary data to the `video` element, but since we can't guarantee that all videos will have the same mime type, we can't safely combine their data.

I can do some more tests with throttling to see how much the preloading helps, but I think the best we can do for now is to ease the transition.
